### PR TITLE
Android Port Improvements

### PR DESCRIPTION
**Pull request by MaysLastPlay**
List of things i updated: 
some options substates
playstate (hitbox won't be visible until countdown started)
main (some phones doesn't support 120fps so it'll be better to set it to 60fps)
project.xml (gradle thing and sdk)
probably will do more things but not for now

### CODE REVIEW

**Comment by MaysLastPlay** [comment]
> a lot of these would break the engine for desktop so this pull request will probably not be possible

that's why pr is a draft lol

**Comment by MaysLastPlay** [comment]
> I don't think it's a good idea to modify things related to FPS, many phones already have 120FPS(Hz) technology.

not really, most of phones have 90hz only.

**Comment by iamteles** [comment]
> I don't think it's a good idea to modify things related to FPS, many phones already have 120FPS(Hz) technology.

pretty sure the engine is meant to run at 120 fps internally so all the tweens will break when its set to 60 fps

**Comment by iamteles** [comment]
not gonna pull this pr but i will add some of these things manually once i resume work on the port

**Pull request closed without merging**
